// Code generated by Kitex v0.10.3. DO NOT EDIT.

package workflowservice

import (
	"context"
	"errors"
	workflowsvc "github.com/aiagt/aiagt/kitex_gen/workflowsvc"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"CallWorkflow": kitex.NewMethodInfo(
		callWorkflowHandler,
		newWorkflowServiceCallWorkflowArgs,
		newWorkflowServiceCallWorkflowResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	workflowServiceServiceInfo                = NewServiceInfo()
	workflowServiceServiceInfoForClient       = NewServiceInfoForClient()
	workflowServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return workflowServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return workflowServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return workflowServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "WorkflowService"
	handlerType := (*workflowsvc.WorkflowService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "workflowsvc",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.10.3",
		Extra:           extra,
	}
	return svcInfo
}

func callWorkflowHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*workflowsvc.WorkflowServiceCallWorkflowArgs)
	realResult := result.(*workflowsvc.WorkflowServiceCallWorkflowResult)
	success, err := handler.(workflowsvc.WorkflowService).CallWorkflow(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newWorkflowServiceCallWorkflowArgs() interface{} {
	return workflowsvc.NewWorkflowServiceCallWorkflowArgs()
}

func newWorkflowServiceCallWorkflowResult() interface{} {
	return workflowsvc.NewWorkflowServiceCallWorkflowResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CallWorkflow(ctx context.Context, req *workflowsvc.CallWorkflowReq) (r *workflowsvc.CallWorkflowResp, err error) {
	var _args workflowsvc.WorkflowServiceCallWorkflowArgs
	_args.Req = req
	var _result workflowsvc.WorkflowServiceCallWorkflowResult
	if err = p.c.Call(ctx, "CallWorkflow", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
