// Code generated by Kitex v0.10.0. DO NOT EDIT.

package modelservice

import (
	"context"
	"errors"
	"fmt"
	base "github.com/aiagt/aiagt/kitex_gen/base"
	modelsvc "github.com/aiagt/aiagt/kitex_gen/modelsvc"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GenToken": kitex.NewMethodInfo(
		genTokenHandler,
		newModelServiceGenTokenArgs,
		newModelServiceGenTokenResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Chat": kitex.NewMethodInfo(
		chatHandler,
		newModelServiceChatArgs,
		newModelServiceChatResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingServer),
	),
	"CreateModel": kitex.NewMethodInfo(
		createModelHandler,
		newModelServiceCreateModelArgs,
		newModelServiceCreateModelResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateModel": kitex.NewMethodInfo(
		updateModelHandler,
		newModelServiceUpdateModelArgs,
		newModelServiceUpdateModelResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteModel": kitex.NewMethodInfo(
		deleteModelHandler,
		newModelServiceDeleteModelArgs,
		newModelServiceDeleteModelResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetModelByID": kitex.NewMethodInfo(
		getModelByIDHandler,
		newModelServiceGetModelByIDArgs,
		newModelServiceGetModelByIDResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListModel": kitex.NewMethodInfo(
		listModelHandler,
		newModelServiceListModelArgs,
		newModelServiceListModelResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetAPIKeyBySource": kitex.NewMethodInfo(
		getAPIKeyBySourceHandler,
		newModelServiceGetAPIKeyBySourceArgs,
		newModelServiceGetAPIKeyBySourceResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetAPIKeyByModel": kitex.NewMethodInfo(
		getAPIKeyByModelHandler,
		newModelServiceGetAPIKeyByModelArgs,
		newModelServiceGetAPIKeyByModelResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	modelServiceServiceInfo                = NewServiceInfo()
	modelServiceServiceInfoForClient       = NewServiceInfoForClient()
	modelServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return modelServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return modelServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return modelServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(true, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "ModelService"
	handlerType := (*modelsvc.ModelService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "modelsvc",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.10.0",
		Extra:           extra,
	}
	return svcInfo
}

func genTokenHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*modelsvc.ModelServiceGenTokenArgs)
	realResult := result.(*modelsvc.ModelServiceGenTokenResult)
	success, err := handler.(modelsvc.ModelService).GenToken(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newModelServiceGenTokenArgs() interface{} {
	return modelsvc.NewModelServiceGenTokenArgs()
}

func newModelServiceGenTokenResult() interface{} {
	return modelsvc.NewModelServiceGenTokenResult()
}

func chatHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	st, ok := arg.(*streaming.Args)
	if !ok {
		return errors.New("ModelService.Chat is a thrift streaming method, please call with Kitex StreamClient")
	}
	stream := &modelServiceChatServer{st.Stream}
	req := new(modelsvc.ChatReq)
	if err := st.Stream.RecvMsg(req); err != nil {
		return err
	}
	return handler.(modelsvc.ModelService).Chat(req, stream)
}

type modelServiceChatClient struct {
	streaming.Stream
}

func (x *modelServiceChatClient) DoFinish(err error) {
	if finisher, ok := x.Stream.(streaming.WithDoFinish); ok {
		finisher.DoFinish(err)
	} else {
		panic(fmt.Sprintf("streaming.WithDoFinish is not implemented by %T", x.Stream))
	}
}
func (x *modelServiceChatClient) Recv() (*modelsvc.ChatResp, error) {
	m := new(modelsvc.ChatResp)
	return m, x.Stream.RecvMsg(m)
}

type modelServiceChatServer struct {
	streaming.Stream
}

func (x *modelServiceChatServer) Send(m *modelsvc.ChatResp) error {
	return x.Stream.SendMsg(m)
}

func newModelServiceChatArgs() interface{} {
	return modelsvc.NewModelServiceChatArgs()
}

func newModelServiceChatResult() interface{} {
	return modelsvc.NewModelServiceChatResult()
}

func createModelHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*modelsvc.ModelServiceCreateModelArgs)
	realResult := result.(*modelsvc.ModelServiceCreateModelResult)
	success, err := handler.(modelsvc.ModelService).CreateModel(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newModelServiceCreateModelArgs() interface{} {
	return modelsvc.NewModelServiceCreateModelArgs()
}

func newModelServiceCreateModelResult() interface{} {
	return modelsvc.NewModelServiceCreateModelResult()
}

func updateModelHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*modelsvc.ModelServiceUpdateModelArgs)
	realResult := result.(*modelsvc.ModelServiceUpdateModelResult)
	success, err := handler.(modelsvc.ModelService).UpdateModel(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newModelServiceUpdateModelArgs() interface{} {
	return modelsvc.NewModelServiceUpdateModelArgs()
}

func newModelServiceUpdateModelResult() interface{} {
	return modelsvc.NewModelServiceUpdateModelResult()
}

func deleteModelHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*modelsvc.ModelServiceDeleteModelArgs)
	realResult := result.(*modelsvc.ModelServiceDeleteModelResult)
	success, err := handler.(modelsvc.ModelService).DeleteModel(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newModelServiceDeleteModelArgs() interface{} {
	return modelsvc.NewModelServiceDeleteModelArgs()
}

func newModelServiceDeleteModelResult() interface{} {
	return modelsvc.NewModelServiceDeleteModelResult()
}

func getModelByIDHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*modelsvc.ModelServiceGetModelByIDArgs)
	realResult := result.(*modelsvc.ModelServiceGetModelByIDResult)
	success, err := handler.(modelsvc.ModelService).GetModelByID(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newModelServiceGetModelByIDArgs() interface{} {
	return modelsvc.NewModelServiceGetModelByIDArgs()
}

func newModelServiceGetModelByIDResult() interface{} {
	return modelsvc.NewModelServiceGetModelByIDResult()
}

func listModelHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*modelsvc.ModelServiceListModelArgs)
	realResult := result.(*modelsvc.ModelServiceListModelResult)
	success, err := handler.(modelsvc.ModelService).ListModel(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newModelServiceListModelArgs() interface{} {
	return modelsvc.NewModelServiceListModelArgs()
}

func newModelServiceListModelResult() interface{} {
	return modelsvc.NewModelServiceListModelResult()
}

func getAPIKeyBySourceHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*modelsvc.ModelServiceGetAPIKeyBySourceArgs)
	realResult := result.(*modelsvc.ModelServiceGetAPIKeyBySourceResult)
	success, err := handler.(modelsvc.ModelService).GetAPIKeyBySource(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newModelServiceGetAPIKeyBySourceArgs() interface{} {
	return modelsvc.NewModelServiceGetAPIKeyBySourceArgs()
}

func newModelServiceGetAPIKeyBySourceResult() interface{} {
	return modelsvc.NewModelServiceGetAPIKeyBySourceResult()
}

func getAPIKeyByModelHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*modelsvc.ModelServiceGetAPIKeyByModelArgs)
	realResult := result.(*modelsvc.ModelServiceGetAPIKeyByModelResult)
	success, err := handler.(modelsvc.ModelService).GetAPIKeyByModel(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newModelServiceGetAPIKeyByModelArgs() interface{} {
	return modelsvc.NewModelServiceGetAPIKeyByModelArgs()
}

func newModelServiceGetAPIKeyByModelResult() interface{} {
	return modelsvc.NewModelServiceGetAPIKeyByModelResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GenToken(ctx context.Context, req *modelsvc.GenTokenReq) (r *modelsvc.GenTokenResp, err error) {
	var _args modelsvc.ModelServiceGenTokenArgs
	_args.Req = req
	var _result modelsvc.ModelServiceGenTokenResult
	if err = p.c.Call(ctx, "GenToken", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Chat(ctx context.Context, req *modelsvc.ChatReq) (ModelService_ChatClient, error) {
	streamClient, ok := p.c.(client.Streaming)
	if !ok {
		return nil, fmt.Errorf("client not support streaming")
	}
	res := new(streaming.Result)
	err := streamClient.Stream(ctx, "Chat", nil, res)
	if err != nil {
		return nil, err
	}
	stream := &modelServiceChatClient{res.Stream}

	if err := stream.Stream.SendMsg(req); err != nil {
		return nil, err
	}
	if err := stream.Stream.Close(); err != nil {
		return nil, err
	}
	return stream, nil
}

func (p *kClient) CreateModel(ctx context.Context, req *modelsvc.CreateModelReq) (r *base.Empty, err error) {
	var _args modelsvc.ModelServiceCreateModelArgs
	_args.Req = req
	var _result modelsvc.ModelServiceCreateModelResult
	if err = p.c.Call(ctx, "CreateModel", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateModel(ctx context.Context, req *modelsvc.UpdateModelReq) (r *base.Empty, err error) {
	var _args modelsvc.ModelServiceUpdateModelArgs
	_args.Req = req
	var _result modelsvc.ModelServiceUpdateModelResult
	if err = p.c.Call(ctx, "UpdateModel", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteModel(ctx context.Context, req *base.IDReq) (r *base.Empty, err error) {
	var _args modelsvc.ModelServiceDeleteModelArgs
	_args.Req = req
	var _result modelsvc.ModelServiceDeleteModelResult
	if err = p.c.Call(ctx, "DeleteModel", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetModelByID(ctx context.Context, req *base.IDReq) (r *modelsvc.Model, err error) {
	var _args modelsvc.ModelServiceGetModelByIDArgs
	_args.Req = req
	var _result modelsvc.ModelServiceGetModelByIDResult
	if err = p.c.Call(ctx, "GetModelByID", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListModel(ctx context.Context, req *modelsvc.ListModelReq) (r *modelsvc.ListModelResp, err error) {
	var _args modelsvc.ModelServiceListModelArgs
	_args.Req = req
	var _result modelsvc.ModelServiceListModelResult
	if err = p.c.Call(ctx, "ListModel", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetAPIKeyBySource(ctx context.Context, req *modelsvc.GetAPIKeyBySourceReq) (r *modelsvc.APIKey, err error) {
	var _args modelsvc.ModelServiceGetAPIKeyBySourceArgs
	_args.Req = req
	var _result modelsvc.ModelServiceGetAPIKeyBySourceResult
	if err = p.c.Call(ctx, "GetAPIKeyBySource", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetAPIKeyByModel(ctx context.Context, req *modelsvc.GetAPIKeyByModelReq) (r *modelsvc.APIKey, err error) {
	var _args modelsvc.ModelServiceGetAPIKeyByModelArgs
	_args.Req = req
	var _result modelsvc.ModelServiceGetAPIKeyByModelResult
	if err = p.c.Call(ctx, "GetAPIKeyByModel", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
