// Code generated by tools/init_service. DO NOT EDIT.

package handler

import "github.com/aiagt/aiagt/common/bizerr"

const (
	ServiceName = "workflow"

	bizCodeCallWorkflow = 0
)

var (
	bizCallWorkflow *bizerr.Biz
)

func initServiceBusiness(serviceCode int) {
	baseCode := (serviceCode + 100) * 100

	bizCallWorkflow = bizerr.NewBiz(ServiceName, "call_workflow", baseCode+bizCodeCallWorkflow)
}
