# config.yml
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: cloudwego
    pipeline_stages:
      - json:
          expressions:
            level: level
            ts: ts
      - labels:
          level:
      - timestamp:
          source: ts
          format: Unix
    static_configs:
      - targets:
          - localhost
        labels:
          __path__: /logs/*.log
