services:
  mysql:
    image: mysql:8.3.0
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf/my.cnf:/etc/my.cnf
    networks:
      - aiagt-network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aiagt

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    user: root
    volumes:
      - ./redis/data:/data
    networks:
      - aiagt-network

  consul:
    image: hashicorp/consul:latest
    ports:
      - 8500:8500
    environment:
      CONSUL_BIND_INTERFACE: eth0
    volumes:
      - ./consul/data:/consul/data
    networks:
      - aiagt-network

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    user: root
    networks:
      - aiagt-network

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - ./grafana/data:/var/lib/grafana
    ports:
      - "3000:3000"
    user: root
    networks:
      - aiagt-network

  jaeger-all-in-one:
    container_name: jaeger-all-in-one
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    networks:
      - aiagt-network

  loki:
    image: grafana/loki:2.9.2
    volumes:
      - ./config/loki.yml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    user: root
    networks:
      - aiagt-network

  promtail:
    image: grafana/promtail:2.9.2
    volumes:
      - ./config/promtail.yml:/etc/promtail/config.yml
      - ./log:/logs
    command: -config.file=/etc/promtail/config.yml
    networks:
      - aiagt-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs
    networks:
      - aiagt-network

networks:
  aiagt-network:
    name: aiagt-network
    driver: bridge