services:
  mysql:
    image: mysql:8.3.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aiagt

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  consul:
    image: hashicorp/consul:latest
    ports:
      - 8500:8500
    environment:
      CONSUL_BIND_INTERFACE: eth0
