services:
  gateway:
    image: aiagt-gateway:latest
    networks:
      - aiagt-network
    volumes:
      - ./log/gateway:/app/log
    ports:
      - 8930:80

  user:
    image: aiagt-user:latest
    networks:
      - aiagt-network
    volumes:
      - ./log/user:/app/log
    ports:
      - 8931:80

  plugin:
    image: aiagt-plugin:latest
    networks:
      - aiagt-network
    volumes:
      - ./log/plugin:/app/log
    ports:
      - 8932:80

  app:
    image: aiagt-app:latest
    networks:
      - aiagt-network
    volumes:
      - ./log/app:/app/log
    ports:
      - 8933:80

  chat:
    image: aiagt-chat:latest
    networks:
      - aiagt-network
    volumes:
      - ./log/chat:/app/log
    ports:
      - 8934:80

  model:
    image: aiagt-model:latest
    networks:
      - aiagt-network
    volumes:
      - ./log/model:/app/log
    ports:
      - 8935:80

networks:
  aiagt-network:
    external: true