// Code generated by tools/init_service. DO NOT EDIT.

package handler

import "github.com/aiagt/aiagt/common/bizerr"

const (
	ServiceName = "user"

	bizCodeDeleteSecret  = 0
	bizCodeGenToken      = 1
	bizCodeGetUser       = 2
	bizCodeGetUserById   = 3
	bizCodeGetUserByIds  = 4
	bizCodeListSecret    = 5
	bizCodeLogin         = 6
	bizCodeParseToken    = 7
	bizCodeRegister      = 8
	bizCodeResetPassword = 9
	bizCodeSaveSecrets   = 10
	bizCodeSendCaptcha   = 11
	bizCodeUpdateUser    = 12
)

var (
	bizDeleteSecret  *bizerr.Biz
	bizGenToken      *bizerr.Biz
	bizGetUser       *bizerr.Biz
	bizGetUserById   *bizerr.Biz
	bizGetUserByIds  *bizerr.Biz
	bizListSecret    *bizerr.Biz
	bizLogin         *bizerr.Biz
	bizParseToken    *bizerr.Biz
	bizRegister      *bizerr.Biz
	bizResetPassword *bizerr.Biz
	bizSaveSecrets   *bizerr.Biz
	bizSendCaptcha   *bizerr.Biz
	bizUpdateUser    *bizerr.Biz
)

func initServiceBusiness(serviceCode int) {
	baseCode := (serviceCode + 100) * 100

	bizDeleteSecret = bizerr.NewBiz(ServiceName, "delete_secret", baseCode+bizCodeDeleteSecret)
	bizGenToken = bizerr.NewBiz(ServiceName, "gen_token", baseCode+bizCodeGenToken)
	bizGetUser = bizerr.NewBiz(ServiceName, "get_user", baseCode+bizCodeGetUser)
	bizGetUserById = bizerr.NewBiz(ServiceName, "get_user_by_id", baseCode+bizCodeGetUserById)
	bizGetUserByIds = bizerr.NewBiz(ServiceName, "get_user_by_ids", baseCode+bizCodeGetUserByIds)
	bizListSecret = bizerr.NewBiz(ServiceName, "list_secret", baseCode+bizCodeListSecret)
	bizLogin = bizerr.NewBiz(ServiceName, "login", baseCode+bizCodeLogin)
	bizParseToken = bizerr.NewBiz(ServiceName, "parse_token", baseCode+bizCodeParseToken)
	bizRegister = bizerr.NewBiz(ServiceName, "register", baseCode+bizCodeRegister)
	bizResetPassword = bizerr.NewBiz(ServiceName, "reset_password", baseCode+bizCodeResetPassword)
	bizSaveSecrets = bizerr.NewBiz(ServiceName, "save_secrets", baseCode+bizCodeSaveSecrets)
	bizSendCaptcha = bizerr.NewBiz(ServiceName, "send_captcha", baseCode+bizCodeSendCaptcha)
	bizUpdateUser = bizerr.NewBiz(ServiceName, "update_user", baseCode+bizCodeUpdateUser)
}
