// Code generated by tools/init_service. DO NOT EDIT.

package handler

import "github.com/aiagt/aiagt/common/bizerr"

const (
	ServiceName = "user"

	bizCodeCreateSecret  = 0
	bizCodeDeleteSecret  = 1
	bizCodeGetUser       = 2
	bizCodeGetUserByID   = 3
	bizCodeGetUserByIds  = 4
	bizCodeListSecret    = 5
	bizCodeLogin         = 6
	bizCodeRegister      = 7
	bizCodeResetPassword = 8
	bizCodeSendCaptcha   = 9
	bizCodeUpdateSecret  = 10
	bizCodeUpdateUser    = 11
)

var (
	bizCreateSecret  *bizerr.Biz
	bizDeleteSecret  *bizerr.Biz
	bizGetUser       *bizerr.Biz
	bizGetUserByID   *bizerr.Biz
	bizGetUserByIds  *bizerr.Biz
	bizListSecret    *bizerr.Biz
	bizLogin         *bizerr.Biz
	bizRegister      *bizerr.Biz
	bizResetPassword *bizerr.Biz
	bizSendCaptcha   *bizerr.Biz
	bizUpdateSecret  *bizerr.Biz
	bizUpdateUser    *bizerr.Biz
)

func initServiceBusiness(serviceCode int) {
	baseCode := (serviceCode + 100) * 100

	bizCreateSecret = bizerr.NewBiz(ServiceName, "create_secret", baseCode+bizCodeCreateSecret)
	bizDeleteSecret = bizerr.NewBiz(ServiceName, "delete_secret", baseCode+bizCodeDeleteSecret)
	bizGetUser = bizerr.NewBiz(ServiceName, "get_user", baseCode+bizCodeGetUser)
	bizGetUserByID = bizerr.NewBiz(ServiceName, "get_user_by_id", baseCode+bizCodeGetUserByID)
	bizGetUserByIds = bizerr.NewBiz(ServiceName, "get_user_by_ids", baseCode+bizCodeGetUserByIds)
	bizListSecret = bizerr.NewBiz(ServiceName, "list_secret", baseCode+bizCodeListSecret)
	bizLogin = bizerr.NewBiz(ServiceName, "login", baseCode+bizCodeLogin)
	bizRegister = bizerr.NewBiz(ServiceName, "register", baseCode+bizCodeRegister)
	bizResetPassword = bizerr.NewBiz(ServiceName, "reset_password", baseCode+bizCodeResetPassword)
	bizSendCaptcha = bizerr.NewBiz(ServiceName, "send_captcha", baseCode+bizCodeSendCaptcha)
	bizUpdateSecret = bizerr.NewBiz(ServiceName, "update_secret", baseCode+bizCodeUpdateSecret)
	bizUpdateUser = bizerr.NewBiz(ServiceName, "update_user", baseCode+bizCodeUpdateUser)
}
