// Code generated by tools/init_service. DO NOT EDIT.

package handler

import "github.com/aiagt/aiagt/common/bizerr"

const (
	ServiceName = "plugin"

	bizCodeCallPluginTool  = 0
	bizCodeCreatePlugin    = 1
	bizCodeCreateTool      = 2
	bizCodeDeletePlugin    = 3
	bizCodeDeleteTool      = 4
	bizCodeGetPluginByID   = 5
	bizCodeGetToolByID     = 6
	bizCodeListPlugin      = 7
	bizCodeListPluginLabel = 8
	bizCodeListPluginTool  = 9
	bizCodePublishPlugin   = 10
	bizCodeTestPluginTool  = 11
	bizCodeUpdatePlugin    = 12
	bizCodeUpdateTool      = 13
)

var (
	bizCallPluginTool  *bizerr.Biz
	bizCreatePlugin    *bizerr.Biz
	bizCreateTool      *bizerr.Biz
	bizDeletePlugin    *bizerr.Biz
	bizDeleteTool      *bizerr.Biz
	bizGetPluginByID   *bizerr.Biz
	bizGetToolByID     *bizerr.Biz
	bizListPlugin      *bizerr.Biz
	bizListPluginLabel *bizerr.Biz
	bizListPluginTool  *bizerr.Biz
	bizPublishPlugin   *bizerr.Biz
	bizTestPluginTool  *bizerr.Biz
	bizUpdatePlugin    *bizerr.Biz
	bizUpdateTool      *bizerr.Biz
)

func initServiceBusiness(serviceCode int) {
	baseCode := (serviceCode + 100) * 100

	bizCallPluginTool = bizerr.NewBiz(ServiceName, "call_plugin_tool", baseCode+bizCodeCallPluginTool)
	bizCreatePlugin = bizerr.NewBiz(ServiceName, "create_plugin", baseCode+bizCodeCreatePlugin)
	bizCreateTool = bizerr.NewBiz(ServiceName, "create_tool", baseCode+bizCodeCreateTool)
	bizDeletePlugin = bizerr.NewBiz(ServiceName, "delete_plugin", baseCode+bizCodeDeletePlugin)
	bizDeleteTool = bizerr.NewBiz(ServiceName, "delete_tool", baseCode+bizCodeDeleteTool)
	bizGetPluginByID = bizerr.NewBiz(ServiceName, "get_plugin_by_id", baseCode+bizCodeGetPluginByID)
	bizGetToolByID = bizerr.NewBiz(ServiceName, "get_tool_by_id", baseCode+bizCodeGetToolByID)
	bizListPlugin = bizerr.NewBiz(ServiceName, "list_plugin", baseCode+bizCodeListPlugin)
	bizListPluginLabel = bizerr.NewBiz(ServiceName, "list_plugin_label", baseCode+bizCodeListPluginLabel)
	bizListPluginTool = bizerr.NewBiz(ServiceName, "list_plugin_tool", baseCode+bizCodeListPluginTool)
	bizPublishPlugin = bizerr.NewBiz(ServiceName, "publish_plugin", baseCode+bizCodePublishPlugin)
	bizTestPluginTool = bizerr.NewBiz(ServiceName, "test_plugin_tool", baseCode+bizCodeTestPluginTool)
	bizUpdatePlugin = bizerr.NewBiz(ServiceName, "update_plugin", baseCode+bizCodeUpdatePlugin)
	bizUpdateTool = bizerr.NewBiz(ServiceName, "update_tool", baseCode+bizCodeUpdateTool)
}
