// Code generated by tools/init_service. DO NOT EDIT.

package handler

import "github.com/aiagt/aiagt/common/bizerr"

const (
	ServiceName = "model"

	bizCodeChat         = 0
	bizCodeCreateModel  = 1
	bizCodeDeleteModel  = 2
	bizCodeGenToken     = 3
	bizCodeGetModelByID = 4
	bizCodeListModel    = 5
	bizCodeUpdateModel  = 6
)

var (
	bizChat         *bizerr.Biz
	bizCreateModel  *bizerr.Biz
	bizDeleteModel  *bizerr.Biz
	bizGenToken     *bizerr.Biz
	bizGetModelByID *bizerr.Biz
	bizListModel    *bizerr.Biz
	bizUpdateModel  *bizerr.Biz
)

func initServiceBusiness(serviceCode int) {
	baseCode := (serviceCode + 100) * 100

	bizChat = bizerr.NewBiz(ServiceName, "chat", baseCode+bizCodeChat)
	bizCreateModel = bizerr.NewBiz(ServiceName, "create_model", baseCode+bizCodeCreateModel)
	bizDeleteModel = bizerr.NewBiz(ServiceName, "delete_model", baseCode+bizCodeDeleteModel)
	bizGenToken = bizerr.NewBiz(ServiceName, "gen_token", baseCode+bizCodeGenToken)
	bizGetModelByID = bizerr.NewBiz(ServiceName, "get_model_by_id", baseCode+bizCodeGetModelByID)
	bizListModel = bizerr.NewBiz(ServiceName, "list_model", baseCode+bizCodeListModel)
	bizUpdateModel = bizerr.NewBiz(ServiceName, "update_model", baseCode+bizCodeUpdateModel)
}
