// Code generated by tools/init_service. DO NOT EDIT.

package handler

import "github.com/aiagt/aiagt/common/bizerr"

const (
	ServiceName = "model"

	bizCodeChat     = 0
	bizCodeGenToken = 1
)

var (
	bizChat     *bizerr.Biz
	bizGenToken *bizerr.Biz
)

func initServiceBusiness(serviceCode int) {
	baseCode := (serviceCode + 100) * 100

	bizChat = bizerr.NewBiz(ServiceName, "chat", baseCode+bizCodeChat)
	bizGenToken = bizerr.NewBiz(ServiceName, "gen_token", baseCode+bizCodeGenToken)
}
